import Link from "next/link";
import type { Metadata } from "next";
import RadarCard from "@/components/RadarCard";
import { placeToStation } from "@/lib/arso/placeToStation";
import { getCurrentWeatherByStation } from "@/lib/arso/parseCurrentWeather";
import { getForecast } from "@/lib/arso/parseForecast";

const cities=Object.keys(placeToStation);
export function generateStaticParams(){return cities.map((city)=>({city}));}
export async function generateMetadata({params}:{params:Promise<{city:string}>}):Promise<Metadata>{const {city}=await params;const p=placeToStation[city];const name=p?.displayName||city;return {title:`Vreme ${name} – radarska slika padavin in vremenska napoved`,description:`Preverite trenutno vreme za ${name}, radarsko sliko padavin in vremensko napoved za Slovenijo. Vir podatkov: ARSO / meteo.si.`,alternates:{canonical:`/vreme/${city}`},openGraph:{title:`Vreme ${name} – radarska slika padavin in vremenska napoved`,description:`Preverite trenutno vreme za ${name}, radarsko sliko padavin in vremensko napoved za Slovenijo. Vir podatkov: ARSO / meteo.si.`}}}
export default async function Page({params}:{params:Promise<{city:string}>}){const {city}=await params;const p=placeToStation[city];if(!p)return <div>Kraj ni podprt.</div>;const obs=await getCurrentWeatherByStation(p.nearestStationSlug);const fc=await getForecast();const faq={"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Kako pogosto se osvežujejo vremenski podatki?","acceptedAnswer":{"@type":"Answer","text":"Podatki ARSO samodejnih meteoroloških postaj se praviloma osvežujejo v rednih intervalih. Na strani prikazujemo zadnje razpoložljive podatke vira ARSO / meteo.si."}},{"@type":"Question","name":"Zakaj vreme za moj kraj uporablja drugo meteorološko postajo?","acceptedAnswer":{"@type":"Answer","text":"ARSO nima meteorološke postaje v vsakem slovenskem kraju, zato za posamezen kraj prikažemo najbližjo oziroma najbolj reprezentativno ARSO postajo."}},{"@type":"Question","name":"Ali je radarska slika padavin uradna?","acceptedAnswer":{"@type":"Answer","text":"Da, radarska slika padavin je prikazana iz javnega vira ARSO / meteo.si."}}]};
return <div className="space-y-4"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><h1 className="text-3xl font-bold">Vreme {p.displayName}</h1><section className="rounded bg-white p-3 shadow"><p>{p.note}: {p.nearestStationName}.</p><p>Temperatura: {obs.temperatureC ?? "Ni podatka"} °C</p><p>Vlaga: {obs.humidityPct ?? "Ni podatka"} %</p><p>Zadnja posodobitev: {obs.observedAt ?? "ni podatka"}</p></section><section className="rounded bg-white p-3 shadow"><h2 className="font-semibold">Napoved</h2><p>{fc.forecastText}</p></section><RadarCard/><p className="text-xs">Vir podatkov: <a className="underline" href="https://meteo.arso.gov.si/">ARSO / meteo.si</a></p><div className="flex flex-wrap gap-2">{cities.filter((c)=>c!==city).slice(0,8).map(c=><Link key={c} href={`/vreme/${c}`}>{c}</Link>)}</div></div>}
